apiVersion: apps/v1
kind: Deployment
metadata:
  name: kenny-vote
  namespace: kenny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kenny-vote
  template:
    metadata:
      labels:
        app: kenny-vote
    spec:
      containers:
        - name: vote
          image: knaval/vote-app-vote:latest
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: "kenny-redis-service"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"