name: CI/CD Voting App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    
    #Checkout
    - name: Checkout repository
      uses: actions/checkout@v3

    #Set up Docker Buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    #Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    #Build & Push vote image
    - name: Build and push vote app
      uses: docker/build-push-action@v5
      with:
        context: ./vote
        file: ./vote/Dockerfile
        platforms: linux/amd64
        push: true
        tags: knaval/vote-app-vote:latest

    #Build & Push result image
    - name: Build and push result app
      uses: docker/build-push-action@v5
      with:
        context: ./result
        file: ./result/Dockerfile
        platforms: linux/amd64
        push: true
        tags: knaval/vote-app-result:latest

    #Build & Push worker image
    - name: Build and push worker app
      uses: docker/build-push-action@v5
      with:
        context: ./worker
        file: ./worker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: knaval/vote-app-worker:latest

    #Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    #Update kubeconfig
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --name ironhack-main \
          --region us-west-1

    #Deploy Kubernetes manifests
    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f k8s/ingress/
        kubectl apply -f k8s/redis/
        kubectl apply -f k8s/postgress/
        kubectl apply -f k8s/vote/
        kubectl apply -f k8s/result/
        kubectl apply -f k8s/worker/