name: CI/CD Voting App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    #Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    #Habilitar Buildx (multiplataforma)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    #Login en Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 4. Build & Push Vote App
    - name: Build and push vote app
      uses: docker/build-push-action@v5
      with:
        context: ./vote
        file: ./vote/Dockerfile
        platforms: linux/amd64
        push: true
        tags: knaval/vote-app-vote:latest

    #Build & Push Result App
    - name: Build and push result app
      uses: docker/build-push-action@v5
      with:
        context: ./result
        file: ./result/Dockerfile
        platforms: linux/amd64
        push: true
        tags: knaval/vote-app-result:latest

    #Build & Push Worker App
    - name: Build and push worker app
      uses: docker/build-push-action@v5
      with:
        context: ./worker
        file: ./worker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: knaval/vote-app-worker:latest

    #Configurar credenciales AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    #Autenticarse al cluster EKS
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --name ironhack-main-2 \
          --region us-west-1

    #Clean Deploy - RECOMENDADO PARA LA DEMO
    - name: Reset namespace
      run: |
        kubectl delete namespace kenny --ignore-not-found=true
        kubectl create namespace kenny

    # Manifest Apply
    #Secrets
    - name: Apply Secrets
      run: |
        kubectl apply -f k8s/secrets/

    #Postgres (StorageClass + PVC + Deployment + Service)
    - name: Apply Postgres (Storage + PVC + Deploy + Service)
      run: |
        kubectl apply -f k8s/postgress/storageclass.yaml
        kubectl apply -f k8s/postgress/pvc.yaml
        kubectl apply -f k8s/postgress/deployment.yaml
        kubectl apply -f k8s/postgress/service.yaml


    #Redis
    - name: Apply Redis
      run: |
        kubectl apply -f k8s/redis/
    #Worker
    - name: Apply Worker
      run: |
        kubectl apply -f k8s/worker/
    #Vote App
    - name: Apply Vote App
      run: |
        kubectl apply -f k8s/vote/
    #Result App
    - name: Apply Result App
      run: |
        kubectl apply -f k8s/result/
    #Ingress (AL FINAL SIEMPRE)
    - name: Apply Ingress
      run: |
        kubectl apply -f k8s/ingress/